import type { BreedingCombination, Location, Pal, Resource } from "./types";

export const metadata = {
  appVersion: "0.1.0",
  datasetVersion: "sample-2026-07-17",
  gameVersion: "Sample data - verify against current Palworld release",
  lastUpdated: "2026-07-17",
};

export const locations: Location[] = [
  {
    id: "windswept-hills",
    name: "Windswept Hills",
    region: "Starter Plateau",
    coordinates: { x: 120, y: -480 },
    description: "Sample early-game habitat area.",
    recommendedLevel: "1-10",
  },
  {
    id: "moonless-shore",
    name: "Moonless Shore",
    region: "Coastal Night Habitat",
    coordinates: { x: -210, y: -315 },
    description: "Sample coastal area used to demonstrate night habitats.",
    recommendedLevel: "8-18",
  },
  {
    id: "volcanic-trench",
    name: "Volcanic Trench",
    region: "Mount Obsidian",
    coordinates: { x: -590, y: -520 },
    description: "Sample late-game volcanic location.",
    recommendedLevel: "35+",
  },
  {
    id: "ancient-ruins",
    name: "Ancient Ruins",
    region: "Unknown",
    description: "Information not currently available.",
  },
];

export const resources: Resource[] = [
  {
    id: "wool",
    name: "Wool",
    image: "WO",
    category: "Pal drops",
    description: "A soft crafting material. Sample entry.",
    usedFor: [{ name: "Cloth", type: "item", quantity: 2 }],
    obtainedFrom: [{ type: "pal-drop", name: "Dropped by Lamball", palId: 1 }],
  },
  {
    id: "flame-organ",
    name: "Flame Organ",
    image: "FO",
    category: "Pal drops",
    description: "A heat-producing organ used in fire-related crafting.",
    usedFor: [{ name: "Fire Arrow", type: "item", quantity: 1 }],
    obtainedFrom: [
      { type: "pal-drop", name: "Dropped by Foxparks", palId: 2 },
      { type: "pal-drop", name: "Dropped by Blazamut", palId: 6 },
    ],
  },
  {
    id: "venom-gland",
    name: "Venom Gland",
    image: "VG",
    category: "Pal drops",
    description: "A toxic material used in medicine and poison equipment.",
    usedFor: [{ name: "Poison Arrow", type: "item", quantity: 1 }],
    obtainedFrom: [{ type: "pal-drop", name: "Dropped by Daedream", palId: 3 }],
  },
  {
    id: "ore",
    name: "Ore",
    image: "OR",
    category: "Ores and minerals",
    description: "A mined material used for ingots.",
    usedFor: [{ name: "Ingot", type: "item", quantity: 2 }],
    obtainedFrom: [{ type: "mining", name: "Ore nodes", locationId: "windswept-hills" }],
  },
  {
    id: "ancient-core",
    name: "Ancient Core",
    image: "AC",
    category: "Ancient materials",
    description: "Sample crafted resource for demonstrating resource pages.",
    usedFor: [{ name: "Ancient Technology", type: "technology" }],
    obtainedFrom: [{ type: "crafting", name: "Crafted from rare components", notes: "Sample data only." }],
  },
];

export const pals: Pal[] = [
  {
    id: 1,
    key: "lamball",
    name: "Lamball",
    image: "LB",
    elements: ["Neutral"],
    description: "A fluffy early-game Pal. Sample data entry.",
    workSuitability: [
      { type: "Handiwork", level: 1 },
      { type: "Transporting", level: 1 },
      { type: "Farming", level: 1 },
    ],
    partnerSkill: { name: "Fluffy Shield", description: "Information not currently available." },
    possibleDrops: [{ resourceId: "wool" }],
    habitats: [{ locationId: "windswept-hills", time: "day", notes: "Sample day-only habitat." }],
    breedingPower: 1470,
    eggType: "Common Egg",
    rarity: 1,
    obtainableByBreeding: true,
    obtainableInWild: true,
  },
  {
    id: 2,
    key: "foxparks",
    name: "Foxparks",
    image: "FX",
    elements: ["Fire"],
    description: "A small fire Pal used here to demonstrate drops and kindling.",
    workSuitability: [{ type: "Kindling", level: 1 }],
    possibleDrops: [{ resourceId: "flame-organ" }],
    habitats: [{ locationId: "windswept-hills", time: "both", notes: "Sample both-times habitat." }],
    breedingPower: 1400,
    eggType: "Scorching Egg",
    rarity: 2,
    obtainableByBreeding: true,
    obtainableInWild: true,
  },
  {
    id: 3,
    key: "daedream",
    name: "Daedream",
    image: "DD",
    elements: ["Dark"],
    description: "A night-themed Pal used to demonstrate night habitat filtering.",
    workSuitability: [
      { type: "Handiwork", level: 1 },
      { type: "Transporting", level: 1 },
    ],
    possibleDrops: [{ resourceId: "venom-gland" }],
    habitats: [{ locationId: "moonless-shore", time: "night", notes: "Sample night-only habitat." }],
    breedingPower: 1230,
    eggType: "Dark Egg",
    rarity: 3,
    obtainableByBreeding: true,
    obtainableInWild: true,
  },
  {
    id: 4,
    key: "anubis",
    name: "Anubis",
    image: "AN",
    elements: ["Ground"],
    description: "A high-skill Pal included as a sample breeding target.",
    workSuitability: [
      { type: "Handiwork", level: 4 },
      { type: "Mining", level: 3 },
      { type: "Transporting", level: 2 },
    ],
    possibleDrops: [{ resourceId: "ancient-core", notes: "Sample data only." }],
    habitats: [],
    alphaLocations: [{ locationId: "ancient-ruins", level: 47, notes: "Sample Alpha entry." }],
    breedingPower: 570,
    eggType: "Rocky Egg",
    rarity: 8,
    obtainableByBreeding: true,
    obtainableInWild: false,
    alpha: true,
  },
  {
    id: 5,
    key: "jetragon",
    name: "Jetragon",
    image: "JT",
    elements: ["Dragon"],
    description: "Legendary sample entry for filters and collection tracking.",
    workSuitability: [{ type: "Gathering", level: 3 }],
    possibleDrops: [{ resourceId: "ancient-core" }],
    habitats: [],
    alphaLocations: [{ locationId: "volcanic-trench", level: 50, notes: "Sample legendary Alpha location." }],
    breedingPower: 90,
    eggType: "Dragon Egg",
    rarity: 10,
    obtainableByBreeding: false,
    obtainableInWild: true,
    legendary: true,
    alpha: true,
  },
  {
    id: 6,
    key: "blazamut",
    name: "Blazamut",
    image: "BZ",
    elements: ["Fire"],
    description: "A fire Alpha sample with multiple drops.",
    workSuitability: [
      { type: "Kindling", level: 3 },
      { type: "Mining", level: 4 },
    ],
    possibleDrops: [{ resourceId: "flame-organ" }, { resourceId: "ore" }],
    habitats: [{ locationId: "volcanic-trench", time: "both", notes: "Sample late-game habitat." }],
    alphaLocations: [{ locationId: "volcanic-trench", level: 49 }],
    breedingPower: 10,
    eggType: "Huge Scorching Egg",
    rarity: 9,
    obtainableByBreeding: true,
    obtainableInWild: true,
    alpha: true,
  },
];

export const breeding: BreedingCombination[] = [
  {
    id: "lamball-foxparks-daedream",
    parentAId: 1,
    parentBId: 2,
    childId: 3,
    notes: "Sample combination for calculator behavior.",
  },
  {
    id: "foxparks-daedream-anubis",
    parentAId: 2,
    parentBId: 3,
    childId: 4,
    notes: "Sample combination. Verify before using as game data.",
  },
  {
    id: "anubis-blazamut-jetragon",
    parentAId: 4,
    parentBId: 6,
    childId: 5,
    specialCombination: true,
    notes: "Sample special fixed combination.",
  },
];
