import type { BreedingCombination, Location, Pal, Resource } from "./types";

export const metadata = {
  appVersion: "0.1.1",
  datasetVersion: "paldeck-starter-2026-07-17",
  gameVersion: "Starter Paldeck list with wiki-sourced icons; gameplay details still being verified",
  lastUpdated: "2026-07-17",
};

function icon(name: string) {
  return `https://palworld.wiki.gg/wiki/Special:Redirect/file/${encodeURIComponent(`${name}_icon.png`)}`;
}

function starterPal(
  id: number,
  name: string,
  elements: string[],
  workSuitability: Pal["workSuitability"] = [],
  options: Partial<Pal> = {},
): Pal {
  return {
    id,
    key: name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
    name,
    image: icon(name),
    elements,
    description: options.description || "Information not currently available.",
    workSuitability,
    possibleDrops: options.possibleDrops || [],
    habitats: options.habitats || [],
    breedingPower: options.breedingPower,
    eggType: options.eggType,
    rarity: options.rarity,
    obtainableByBreeding: options.obtainableByBreeding,
    obtainableInWild: options.obtainableInWild,
    alpha: options.alpha,
    legendary: options.legendary,
    alphaLocations: options.alphaLocations,
    partnerSkill: options.partnerSkill,
    butcherDrops: options.butcherDrops,
    variant: options.variant,
    versionIntroduced: options.versionIntroduced,
  };
}

export const locations: Location[] = [
  {
    id: "windswept-hills",
    name: "Windswept Hills",
    region: "Starter Plateau",
    coordinates: { x: 120, y: -480 },
    description: "Sample early-game habitat area.",
    recommendedLevel: "1-10",
  },
  {
    id: "moonless-shore",
    name: "Moonless Shore",
    region: "Coastal Night Habitat",
    coordinates: { x: -210, y: -315 },
    description: "Sample coastal area used to demonstrate night habitats.",
    recommendedLevel: "8-18",
  },
  {
    id: "volcanic-trench",
    name: "Volcanic Trench",
    region: "Mount Obsidian",
    coordinates: { x: -590, y: -520 },
    description: "Sample late-game volcanic location.",
    recommendedLevel: "35+",
  },
  {
    id: "ancient-ruins",
    name: "Ancient Ruins",
    region: "Unknown",
    description: "Information not currently available.",
  },
];

export const resources: Resource[] = [
  {
    id: "wool",
    name: "Wool",
    image: "WO",
    category: "Pal drops",
    description: "A soft crafting material. Sample entry.",
    usedFor: [{ name: "Cloth", type: "item", quantity: 2 }],
    obtainedFrom: [{ type: "pal-drop", name: "Dropped by Lamball", palId: 1 }],
  },
  {
    id: "flame-organ",
    name: "Flame Organ",
    image: "FO",
    category: "Pal drops",
    description: "A heat-producing organ used in fire-related crafting.",
    usedFor: [{ name: "Fire Arrow", type: "item", quantity: 1 }],
    obtainedFrom: [
      { type: "pal-drop", name: "Dropped by Foxparks", palId: 29 },
      { type: "pal-drop", name: "Dropped by Blazamut", palId: 96 },
    ],
  },
  {
    id: "venom-gland",
    name: "Venom Gland",
    image: "VG",
    category: "Pal drops",
    description: "A toxic material used in medicine and poison equipment.",
    usedFor: [{ name: "Poison Arrow", type: "item", quantity: 1 }],
    obtainedFrom: [{ type: "pal-drop", name: "Dropped by Daedream", palId: 22 }],
  },
  {
    id: "ore",
    name: "Ore",
    image: "OR",
    category: "Ores and minerals",
    description: "A mined material used for ingots.",
    usedFor: [{ name: "Ingot", type: "item", quantity: 2 }],
    obtainedFrom: [{ type: "mining", name: "Ore nodes", locationId: "windswept-hills" }],
  },
  {
    id: "ancient-core",
    name: "Ancient Core",
    image: "AC",
    category: "Ancient materials",
    description: "Sample crafted resource for demonstrating resource pages.",
    usedFor: [{ name: "Ancient Technology", type: "technology" }],
    obtainedFrom: [{ type: "crafting", name: "Crafted from rare components", notes: "Sample data only." }],
  },
];

export const pals: Pal[] = [
  starterPal(1, "Lamball", ["Neutral"], [
    { type: "Handiwork", level: 1 },
    { type: "Transporting", level: 1 },
    { type: "Farming", level: 1 },
  ], {
    possibleDrops: [{ resourceId: "wool" }],
    habitats: [{ locationId: "windswept-hills", time: "day", notes: "Starter sample habitat." }],
    rarity: 1,
    eggType: "Common Egg",
    obtainableInWild: true,
    obtainableByBreeding: true,
  }),
  starterPal(2, "Cattiva", ["Neutral"], [{ type: "Handiwork", level: 1 }, { type: "Gathering", level: 1 }, { type: "Mining", level: 1 }, { type: "Transporting", level: 1 }]),
  starterPal(3, "Chikipi", ["Neutral"], [{ type: "Farming", level: 1 }]),
  starterPal(4, "Lifmunk", ["Grass"], [{ type: "Planting", level: 1 }, { type: "Handiwork", level: 1 }, { type: "Gathering", level: 1 }, { type: "Lumbering", level: 1 }, { type: "Medicine Production", level: 1 }]),
  starterPal(5, "Fuack", ["Water"], [{ type: "Watering", level: 1 }, { type: "Handiwork", level: 1 }, { type: "Transporting", level: 1 }]),
  starterPal(6, "Vixy", ["Neutral"], [{ type: "Gathering", level: 1 }, { type: "Farming", level: 1 }]),
  starterPal(7, "Celaray", ["Water"], [{ type: "Watering", level: 1 }, { type: "Transporting", level: 1 }]),
  starterPal(8, "Cremis", ["Neutral"], [{ type: "Gathering", level: 1 }, { type: "Farming", level: 1 }]),
  starterPal(9, "Croajiro", ["Water"], [{ type: "Watering", level: 1 }, { type: "Handiwork", level: 1 }, { type: "Gathering", level: 1 }]),
  starterPal(10, "Herbil", ["Grass"], [{ type: "Planting", level: 1 }, { type: "Gathering", level: 1 }]),
  starterPal(11, "Teafant", ["Water"], [{ type: "Watering", level: 1 }]),
  starterPal(12, "Gumoss", ["Grass"], [{ type: "Planting", level: 1 }]),
  starterPal(13, "Pupperai", ["Dark"], [{ type: "Gathering", level: 1 }, { type: "Transporting", level: 1 }]),
  starterPal(14, "Clovee", ["Grass"], [{ type: "Planting", level: 1 }, { type: "Gathering", level: 1 }]),
  starterPal(15, "Jolthog", ["Electric"], [{ type: "Generating Electricity", level: 1 }]),
  starterPal(16, "Depresso", ["Dark"], [{ type: "Handiwork", level: 1 }, { type: "Mining", level: 1 }, { type: "Transporting", level: 1 }]),
  starterPal(17, "Pengullet", ["Water", "Ice"], [{ type: "Watering", level: 1 }, { type: "Cooling", level: 1 }, { type: "Handiwork", level: 1 }, { type: "Transporting", level: 1 }]),
  starterPal(18, "Penking", ["Water", "Ice"], [{ type: "Watering", level: 2 }, { type: "Cooling", level: 2 }, { type: "Handiwork", level: 2 }, { type: "Mining", level: 2 }, { type: "Transporting", level: 2 }]),
  starterPal(19, "Hoocrates", ["Dark"], [{ type: "Gathering", level: 1 }]),
  starterPal(20, "Melpaca", ["Neutral"], [{ type: "Farming", level: 1 }]),
  starterPal(21, "Kingpaca", ["Neutral"], [{ type: "Gathering", level: 1 }]),
  starterPal(22, "Daedream", ["Dark"], [{ type: "Handiwork", level: 1 }, { type: "Transporting", level: 1 }], {
    possibleDrops: [{ resourceId: "venom-gland" }],
    habitats: [{ locationId: "moonless-shore", time: "night", notes: "Starter sample night habitat." }],
    eggType: "Dark Egg",
    obtainableInWild: true,
    obtainableByBreeding: true,
  }),
  starterPal(23, "Tanzee", ["Grass"], [{ type: "Planting", level: 1 }, { type: "Handiwork", level: 1 }, { type: "Gathering", level: 1 }, { type: "Lumbering", level: 1 }, { type: "Transporting", level: 1 }]),
  starterPal(24, "Nox", ["Dark"], [{ type: "Gathering", level: 1 }]),
  starterPal(25, "Flambelle", ["Fire"], [{ type: "Kindling", level: 1 }, { type: "Handiwork", level: 1 }, { type: "Transporting", level: 1 }]),
  starterPal(26, "Rooby", ["Fire"], [{ type: "Kindling", level: 1 }]),
  starterPal(27, "Mau", ["Dark"], [{ type: "Farming", level: 1 }]),
  starterPal(28, "Rushoar", ["Ground"], [{ type: "Mining", level: 1 }]),
  starterPal(29, "Foxparks", ["Fire"], [{ type: "Kindling", level: 1 }], {
    possibleDrops: [{ resourceId: "flame-organ" }],
    habitats: [{ locationId: "windswept-hills", time: "both", notes: "Starter sample both-times habitat." }],
    eggType: "Scorching Egg",
    obtainableInWild: true,
    obtainableByBreeding: true,
  }),
  starterPal(30, "Killamari", ["Dark"], [{ type: "Gathering", level: 1 }, { type: "Transporting", level: 2 }]),
  starterPal(31, "Fuddler", ["Ground"], [{ type: "Handiwork", level: 1 }, { type: "Mining", level: 1 }, { type: "Transporting", level: 1 }]),
  starterPal(32, "Eikthyrdeer", ["Neutral"], [{ type: "Lumbering", level: 2 }]),
  starterPal(33, "Direhowl", ["Neutral"], [{ type: "Gathering", level: 1 }]),
  starterPal(34, "Caprity", ["Grass"], [{ type: "Planting", level: 2 }, { type: "Farming", level: 1 }]),
  starterPal(35, "Swee", ["Ice"], [{ type: "Cooling", level: 1 }]),
  starterPal(36, "Sweepa", ["Ice"], [{ type: "Cooling", level: 2 }, { type: "Gathering", level: 2 }]),
  starterPal(37, "Turtacle", ["Water"], [{ type: "Watering", level: 1 }, { type: "Mining", level: 1 }]),
  starterPal(96, "Blazamut", ["Fire"], [{ type: "Kindling", level: 3 }, { type: "Mining", level: 4 }], {
    possibleDrops: [{ resourceId: "flame-organ" }, { resourceId: "ore" }],
    habitats: [{ locationId: "volcanic-trench", time: "both", notes: "Starter sample late-game habitat." }],
    alphaLocations: [{ locationId: "volcanic-trench", level: 49 }],
    alpha: true,
  }),
  starterPal(100, "Anubis", ["Ground"], [{ type: "Handiwork", level: 4 }, { type: "Mining", level: 3 }, { type: "Transporting", level: 2 }], {
    habitats: [],
    alphaLocations: [{ locationId: "ancient-ruins", level: 47, notes: "Sample Alpha entry." }],
    alpha: true,
    obtainableByBreeding: true,
    obtainableInWild: false,
  }),
  starterPal(111, "Jetragon", ["Dragon"], [{ type: "Gathering", level: 3 }], {
    habitats: [],
    alphaLocations: [{ locationId: "volcanic-trench", level: 50, notes: "Sample legendary Alpha location." }],
    legendary: true,
    alpha: true,
    obtainableByBreeding: false,
    obtainableInWild: true,
  }),
];

export const breeding: BreedingCombination[] = [
  {
    id: "lamball-foxparks-daedream",
    parentAId: 1,
    parentBId: 29,
    childId: 22,
    notes: "Sample combination for calculator behavior.",
  },
  {
    id: "foxparks-daedream-anubis",
    parentAId: 29,
    parentBId: 22,
    childId: 100,
    notes: "Sample combination. Verify before using as game data.",
  },
  {
    id: "anubis-blazamut-jetragon",
    parentAId: 100,
    parentBId: 96,
    childId: 111,
    specialCombination: true,
    notes: "Sample special fixed combination.",
  },
];
